### ISSUE TITLE
question about extending CollectionViewDataSource

### ISSUE THREAD

**Issue by richellis** [objcio/core-data#1]
Not sure if this is the right forum where readers of your book can discuss questions, but I'm giving it a shot anyway.  :)

I’m using your CollectionViewDataSource generic class with a view controller and I’m stuck trying to extend it. My view controller needs to respond to one of the optional UICollectionViewDataSource methods not implemented in CollectionViewDataSource. I don’t want to add it to CollectionViewDataSource because not all VCs will need to implement it. So I thought I could just extend the class with a `where` restriction for my particular view controller:
```swift
extension CollectionViewDataSource where Delegate: MyViewController {
    func collectionView( … )   // my extra method goes here
}
```
This compiles and seems like it should work based on some playground experimentation, but my method in this extension is never called by the CollectionView.

Any suggestions to make this work, or an alternative approach?

-Rich

**Comment by floriankugler** [comment]
@richellis Sorry for the late reply – holiday season traveling. My guess is that this method is not visible to the objective-c dynamic dispatch. I'm not sure if this is possible, you can try if an `@objc` attribute helps. However, you could just add it to your main data source class and provide a default implementation (that does nothing) for the delegate method as a protocol extension.
