### ISSUE TITLE
Swift 3 errors in multiple Core Data Helper files

### ISSUE THREAD

**Issue by sjmagy** [objcio/core-data#27]
Hello,
A lot of the code from the Core Data book seems to be broken in Swift 3 (I made the mistake of being on the bleeding edge of converting); I think I’ve been able to fix a lot of it, but as someone who is still learning, I’m struggling with some of the errors that XCode is spitting out.

Is there an update planned to the code posted on GitHub?

The specific areas I’m stumped by are:

In file Collection+CoreDataExtensions.swift, in the fetchObjectsThatAreFaults function, XCode complains:  “Generic parameter ‘ResultType’ could not be inferred” for the line:

        let request = NSFetchRequest()

Then, in file NSManagedObjectContext+Observers.swift, the ContextDidSaveNotification function has the error:  "Ambiguous reference to member ‘joined()’” in the line:

        return components.joined(separator: " ")

I’ve managed to (I think) fix the ~20+ other errors that appeared and prevented successful build, but no matter what I do or think I should do to resolve the two above, XCode is not happy, and I’ve scoured the internet to try and find some leads to solutions, but have come up empty.

Thanks for any info you can provide.

**Comment by floriankugler** [comment]
@sjmagy Yes, we’ll update the book for Swift 3 and iOS 10/macOS Sierra later this year.

A lot has changed in Swift 3, and Core Data also received a significant API brush-up for Swift as well as some new features.

For example, `NSFetchRequest` now has a generic parameter `ResultType`, that’s why you’re getting the "Generic parameter ‘ResultType’ could not be inferred” error. If you’d want to fetch objects of type `Person` with this fetch request, you’d have to write:

let fetchRequest: FetchRequest<Person> = NSFetchRequest()

I’d suggest to read up on the topic of generics in Swift as well as the Core Data API changes in the recent releases. You’ll encounter similar things in many places going forward… :-)

As for the second error, there seem to be two functions `joined(separator:)` defined on the type of `components`. However, this whole thing is just part of a `debugDescription` property, so you could always just comment it out for the time being if you can't resolve the error.

**Comment by sjmagy** [comment]
Thank you for the fast response and extra context; hopefully your guidance will help lead this proverbial horse to water.  Glad to hear the book will be updated; I just purchased it earlier this year (before I was aware there would be a Swift 3) and found it immensely helpful.
