### ISSUE TITLE
Issue on Xcode 8.1 DefaultManagedObjectType

### ISSUE THREAD

**Issue by bishalg** [objcio/core-data#30]
Getting following issue while compiling - 

> While emitting IR SIL function @_TToZFE22 DefaultManagedObjectTypeg17aDefaultPredicateCSo11NSPredicate for 'defaultPredicate' at /ManagedObject.swift:23:14

If I comment following code it works - 

```
extension DefaultManagedObjectType {
 static var defaultPredicate: NSPredicate {
    return NSPredicate(value: true)
  }
}
```

**Comment by floriankugler** [comment]
The code has not been updated for Swift 3 yet. We'll push an update in the next days.
