### ISSUE TITLE
cant't compiler 

### ISSUE THREAD

**Issue by aiqiuqiu** [objcio/core-data#31]
项目编译不过找谁 。  这么久也不更新 //////

**Comment by floriankugler** [comment]
The code has not been updated for Swift 3 yet. We'll push an update in the next days.

**Comment by MTSwiftManiac** [comment]
@floriankugler May I known when this book will be updated for Swift 3?

**Comment by floriankugler** [comment]
@MTSwiftManiac The update is done – unfortunately we have to wait for some legal stuff to be sorted out. Sorry for the delay!

**Comment by bobvoorneveld** [comment]
Hi @floriankugler, love the books, love the swift talks, and would love to read the book with at least the code updated to swift 3. I've tried to build the app piece by piece in a new project, but with all the dependencies, it's just too much work to get it done. Do you have any clue when the update will be on github?

**Comment by floriankugler** [comment]
@bobvoorneveld No, we don't, sorry. We're working on an alternative solution, but it's pretty much out of our hands.

**Comment by tkrajacic** [comment]
Ouch :(

**Comment by bobvoorneveld** [comment]
Hi guys, tnx for updating!

**Comment by austinzmchen** [comment]
kudos!
