### ISSUE TITLE
Fragility of using ubiquityToken?

### ISSUE THREAD

**Issue by simme** [objcio/core-data#33]
Quick question regarding the use of `ubiquityToken` as the file name for the persisted store. Won't that mean that if the user changes iCloud account or logs out they will lose all of their data?

I see the reasoning for this, but it seems like if the phone is not wiped it's a fair assumption that the same person is still using the phone.

**Comment by floriankugler** [comment]
Yes, I'd say you have to decide what kind of behavior you want in case of an account change on a per project basis.
