### ISSUE TITLE
TableViewDelegate ?

### ISSUE THREAD

**Issue by koenvanderdrift** [objcio/core-data#4]
I hope this is an ok place to ask questions about the book. Really enjoying it so far and learning a lot.

Would it make sense to use a `TableViewDelegate` similar to `TableViewDataSource` for functions such as `didSelectRowAtIndexPath`, `willDisplayCell`, etc using the `ConfigurableCell` protocol ? Or does it make more sense to just keep these functions inside the `UITableViewController` subclasses ?

**Comment by floriankugler** [comment]
@koenvanderdrift It's hard to answer in the abstract. It depends what you do in response to those delegate calls. If it helps you to avoid writing boilerplate code it could make sense.
