### ISSUE TITLE
Update Sync Shared Code

### ISSUE THREAD

**Issue by bdpluim** [objcio/core-data#6]
More a comment than an issue.  I'm just reading through the book and I'm about half way through.  First off, EXCELLENT work.  Learning a lot and really happy to understand the guts of Core Data better.

I am looking at pulling out pieces into a sample app for more hands on learning and I'm wondering if most of the classes in MoodySync should be considered part of the "SharedCode".  A lot of it isn't really app specific, but more core pieces of the sync process.

The classes I'm talking about are all the classes in the "Sync Engine" folder and all classes in "Helpers" folder.  I see why the ChangeProcessors and the Remote code is application specific.

Thoughts?

**Comment by bdpluim** [comment]
Just digging in and finding that there are some references to the MoodyModel but it seems like most of those references could be turned into generic stuff.  I'll keep plugging on this, but it seems like the SyncEngine itself is so close to being generic, why not just go all the way.

Why not make the ChangeProcessorContextType not be dependent on the MoodyRemoteType?

**Comment by floriankugler** [comment]
@bdpluim I'm sure it's feasible to pull this code out in a totally generic way. This wasn't our goal in this particular project, but it could certainly make sense if you want to reuse this component in multiple places. I'll add a ticket to consider this for future updates!
