### ISSUE TITLE
Setting Up Stack issue

### ISSUE THREAD

**Issue by marcus-grant** [objcio/core-data#7]
Your book on page 20, which details setting up the Core Data stack, mentions a line of code:
`private let StoreURL = NSURL.documentsURL.URLByAppendingPathComponent("Moody.moody")`

This line can't compile because there's nothing inside "NSURL" called documentsURL.

**Comment by floriankugler** [comment]
@marcus-grant This is defined here: https://github.com/objcio/core-data/blob/master/SharedCode/Utilities.swift#L85

We should probably mention that in the book as well... thanks for the hint!

**Comment by marcus-grant** [comment]
Yes please do, it's kind of confusing to follow along with, why isn't it just performing these functions in-line?
