### ISSUE TITLE
Incremental tags per chapter?

### ISSUE THREAD

**Issue by oflannabhra** [objcio/core-data#8]
First of all, I just want to say that I am very impressed with the book, and am very satisfied. I'm consistently impressed (and challenged) by the quality of the code Objc.io has produced over the years.

As I'm working through the book, however, it is difficult to come to this project and maintain a context for what is currently being developed. Would it be possible to see the project not in a final state, but as it is built up and refactored? 

I understand that this is no small request. I think the learning potential of such an undertaking would be relatively huge, though.

**Comment by floriankugler** [comment]
@oflannabhra That's one of the things on our list. We didn't do it for the first iteration, because things were changing too much. We'll definitely consider this going forward. Thanks for the feedback!

**Comment by oflannabhra** [comment]
:+1: man, you guys are awesome! Thanks for being so open and accessible!
